Create sulfurpotassiummod
lukebemish/excavated_variants pull request #28
Opened 2022-04-15 11:17 UTC by cowsha

![изображение](https://user-images.githubusercontent.com/35926994/163564764-8fe34077-2ad6-4cda-886a-71baee0e23f3.png)

2022-04-15 19:04 UTC, lukebemish requested changes
This file appears to not have an extension, unless GitHub is messing with me.

2022-04-15 22:43 UTC, cowsha commented
> This file appears to not have an extension, unless GitHub is messing with me.
might be so, im not really know how to use this

2022-04-15 22:48 UTC, cowsha commented
I guess this is it?
![изображение](https://user-images.githubusercontent.com/35926994/163650403-8f948706-e0a3-461c-a9a4-1db769629e63.png)
![изображение](https://user-images.githubusercontent.com/35926994/163650442-3614f1ba-3890-471c-b180-5e1ad21cf600.png)

2022-04-16 01:07 UTC, lukebemish approved these changes

2022-04-16 01:56 UTC, merged