Update betternether.json
lukebemish/excavated_variants pull request #48
Opened 2022-05-26 09:33 UTC by FluffyBumblee

Fixed a very tiny bug where ruby ores would overlap

2022-05-26 09:48 UTC, FluffyBumblee commented
AE2 Compat added.

2022-05-26 10:15 UTC, FluffyBumblee commented
I'm gonna add industrial revolution support and im done (maybe)

2022-05-26 10:34 UTC, FluffyBumblee commented
Ok I can rest now!

2022-05-26 10:41 UTC, FluffyBumblee commented
Updated fabric to prepare for loader plugins

2022-05-26 16:05 UTC, lukebemish requested changes
You might want to go through and fix some stuff up; I have a script that I use to generate these entries for mods with proper tag entries, so I may go through and redo the indrev and MI ones, but otherwise this looks good.

2022-05-26 16:05 UTC, lukebemish commented on Common/src/main/resources/default_configs/betternether.json
> +      "id": "nether_ruby_ore",
Uness you add an `orename` field, this change will break ore dict compat

2022-05-26 16:05 UTC, lukebemish commented on Common/src/main/resources/default_configs/enriched.json
> +        "deepslate",
Stones need to be in the same order as the blocks

2022-05-26 16:05 UTC, lukebemish commented on Common/src/main/resources/default_configs/enriched.json
> +        "deepslate",
Stones need to be in the same order as the blocks

2022-05-26 16:05 UTC, lukebemish commented on Common/src/main/resources/default_configs/enriched.json
> +        "deepslate",
Stones need to be in the same order as the blocks

2022-05-26 16:05 UTC, lukebemish commented on Common/src/main/resources/default_configs/indrev.json
> +      "id": "sead_ore",
Might want to fix this

2022-05-26 16:05 UTC, lukebemish commented on Common/src/main/resources/default_configs/modern_industrialization.json
> +        "stone"
You need the same number of stones as block ids

2022-05-26 16:05 UTC, lukebemish commented on Common/src/main/resources/default_configs/modern_industrialization.json
> +        "stone"
Same as above

2022-05-26 16:05 UTC, lukebemish commented on changelogs/CHANGELOG.md
> +### Excavated Variants v0.6.3
Leave this out; I'll write my own changelogs

2022-05-26 16:05 UTC, lukebemish commented on gradle.properties
> +fabric_version=0.53.4+1.18.2
Any particular reason this is needed?

2022-05-26 16:07 UTC, lukebemish commented
Also, what are fabric loader plugins and why does the mod need version bumps for this?

2022-05-27 02:24 UTC, FluffyBumblee commented
I'll work on it

2022-05-27 02:25 UTC, FluffyBumblee commented
> Also, what are fabric loader plugins and why does the mod need version bumps for this?

Next version is going to have loader plugins (0.15). I bumped the version to prepare for big changes as I'm sure it'll break things. I undo this if you want.

2022-05-27 02:31 UTC, lukebemish commented
Okay, but what are loader plugins?

2022-05-27 02:42 UTC, lukebemish commented
Ah, did some research; this shouldn't affect me, no reason to bump it unless they make a breaking change

2022-05-27 02:42 UTC, lukebemish commented
Especially since 1.18 support will end fairly soon

2022-05-27 02:48 UTC, FluffyBumblee commented
Alright. I'll reverse it.

2022-05-27 02:49 UTC, lukebemish commented
Cool. It won't matter much in 1.19 anyways, since as soon as curseforge gives me an option Im going to discontinue Fabric support in favor of Quilt.

2022-05-27 02:52 UTC, FluffyBumblee commented
> Cool. It won't matter much in 1.19 anyways, since as soon as curseforge gives me an option I'm going to discontinue Fabric support in favor of Quilt.

Hmmm... that's a bummer. Curseforge supports quilt now FYI. Could I also make a syntax.json so people can just copy it and modify it to add their own support very quickly.

2022-05-27 02:57 UTC, lukebemish commented
What do you mean by that?

2022-05-27 03:00 UTC, FluffyBumblee commented
> What do you mean by that?

So I basically have JSON Scripts for ores and stones but without any ID's and with labels to visual demonstrate how it works.

2022-05-27 03:08 UTC, FluffyBumblee commented
Jesus Christ pull requests give me a headache lol.

2022-05-27 03:21 UTC, FluffyBumblee commented
Alright, the scripts should be fixed. I'll probably make a syntax.json and I'll delete it if you don't want it.

2022-05-27 03:33 UTC, FluffyBumblee commented
Ok, I finished that. Now it's up to review.

2022-05-27 03:36 UTC, FluffyBumblee commented
why is it still looking at the old commits lol.

2022-05-27 03:41 UTC, FluffyBumblee commented
Also. I think you should keep fabric even if you aren't going to support it as some others might maintain it for you.

2022-05-27 03:44 UTC, lukebemish commented
The project is LGPL and they can feel free to do so themselves, but I will not be supporting fabric

2022-05-27 03:47 UTC, lukebemish commented
I'll review it once I'm back at a computer

2022-05-27 04:44 UTC, lukebemish requested changes

2022-05-27 04:44 UTC, lukebemish commented on Common/src/main/resources/default_configs/betternether.json
> +      "id": "nether_ruby_ore",
Okay, I should specify; either add an `orename` field, or revert this change

2022-05-27 04:44 UTC, lukebemish commented on Common/src/main/resources/default_configs/example.json
> +  "mod_id": "", #add mod_id
Can you switch these to java-style comments, with a space after the `//`?

2022-05-27 04:44 UTC, lukebemish commented on Common/src/main/resources/default_configs/example.json
> +	  "en_name": "", #Actual Name, e.g. Ruby Ore
It's the english translation name, not so much the "actual name"

2022-05-27 04:44 UTC, lukebemish commented on Common/src/main/resources/default_configs/example.json
> +        "deepslate", #add the stone types that this ore already has.
And yet, they're not in the same order here

2022-05-27 04:44 UTC, lukebemish commented on Common/src/main/resources/default_configs/example.json
> +	  "id": "modid_itemid", #Don't add ":"
That's not what the ID is. The ID is an identifier for the stone. It should be unique. It has nothing to do with the mod/item ID; that's just a convention I follow to guarantee uniqueness

2022-05-27 04:44 UTC, lukebemish commented on Common/src/main/resources/default_configs/example.json
> +	  "en_name": "", #Actual name, e.g. "Dark Granite
Close quote here

2022-05-27 04:44 UTC, lukebemish commented on Common/src/main/resources/default_configs/example.json
> +        "stone" #stone=overworld, end=end,nether=nether. Add the following for the dimension the blocks will spawn in
It has nothing to do with the dimension; it is a category for the stone that associates ores with stones.

2022-05-27 04:44 UTC, lukebemish commented on gradle.properties
> +fabric_version=0.51.1+1.18.2
Might want to revert this change; no reason to break backwards compat if I don't need to

2022-05-27 06:10 UTC, FluffyBumblee commented
Alright that should do it.

2022-05-27 06:14 UTC, lukebemish commented on Common/src/main/resources/default_configs/example.json
> +	  "id": "modid_itemid", #Don't add ":"
This was meant for the ID, not the modid

2022-05-27 06:22 UTC, FluffyBumblee commented
I was so close to +420 lines lmao

2022-05-27 21:55 UTC, merged